In [1]:
import numpy as np

In [2]:
# Creating a 1D array
arr_1d = np.array([10, 20, 30, 40, 50])

print("1D Array:", arr_1d)
print("Shape:", arr_1d.shape)

1D Array: [10 20 30 40 50]
Shape: (5,)


In [3]:
# Creating a 2D array
arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("2D Array:")
print(arr_2d)
print("Shape:", arr_2d.shape)

2D Array:
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)


In [4]:
# Indexing
print("First element:", arr_1d[0])
print("Third element:", arr_1d[2])

# 2D indexing
print("First row:", arr_2d[0])
print("Element at row 2, column 3:", arr_2d[1, 2])

First element: 10
Third element: 30
First row: [10 20 30]
Element at row 2, column 3: 60


In [5]:
# Slicing
print("First three elements:", arr_1d[:3])
print("Elements from index 2:", arr_1d[2:])
print("2D slice:")
print(arr_2d[:, 1:])

First three elements: [10 20 30]
Elements from index 2: [30 40 50]
2D slice:
[[20 30]
 [50 60]]


In [6]:
# Mathematical operations
print("Addition:", arr_1d + 5)
print("Subtraction:", arr_1d - 5)
print("Multiplication:", arr_1d * 2)
print("Division:", arr_1d / 2)

Addition: [15 25 35 45 55]
Subtraction: [ 5 15 25 35 45]
Multiplication: [ 20  40  60  80 100]
Division: [ 5. 10. 15. 20. 25.]


In [7]:
# Aggregation functions
print("Sum:", np.sum(arr_1d))
print("Mean:", np.mean(arr_1d))
print("Maximum:", np.max(arr_1d))
print("Minimum:", np.min(arr_1d))

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [8]:
# Python List vs NumPy Array

python_list = [10, 20, 30]
numpy_array = np.array([10, 20, 30])

print("Python List * 2:", python_list * 2)
print("NumPy Array * 2:", numpy_array * 2)

Python List * 2: [10, 20, 30, 10, 20, 30]
NumPy Array * 2: [20 40 60]
