In [1]:
import numpy as np

In [2]:
import numpy as np

# Student marks
students = np.array([
    [85, 90, 78, 88, 92],
    [72, 68, 75, 80, 70],
    [95, 92, 96, 90, 94],
    [60, 65, 58, 70, 62],
    [88, 84, 90, 86, 91]
])

print("Student Marks:")
print(students)

# Total marks for each student
total_marks = np.sum(students, axis=1)
print("\nTotal Marks:")
print(total_marks)

# Average marks for each student
average_marks = np.mean(students, axis=1)
print("\nAverage Marks:")
print(average_marks)

# Highest and lowest marks
print("\nHighest Mark:", np.max(students))
print("Lowest Mark:", np.min(students))

# Subject-wise average
subject_average = np.mean(students, axis=0)
print("\nSubject-wise Average:")
print(subject_average)

# Top student
top_student = np.argmax(average_marks)
print("\nTop Student: Student", top_student + 1)
print("Highest Average:", average_marks[top_student])

# Grade
print("\nGrades:")
for i, avg in enumerate(average_marks):
    if avg >= 90:
        grade = "A+"
    elif avg >= 80:
        grade = "A"
    elif avg >= 70:
        grade = "B"
    elif avg >= 60:
        grade = "C"
    elif avg >= 50:
        grade = "D"
    else:
        grade = "F"

    print(f"Student {i + 1}: {grade}")

Student Marks:
[[85 90 78 88 92]
 [72 68 75 80 70]
 [95 92 96 90 94]
 [60 65 58 70 62]
 [88 84 90 86 91]]

Total Marks:
[433 365 467 315 439]

Average Marks:
[86.6 73.  93.4 63.  87.8]

Highest Mark: 96
Lowest Mark: 58

Subject-wise Average:
[80.  79.8 79.4 82.8 81.8]

Top Student: Student 3
Highest Average: 93.4

Grades:
Student 1: A
Student 2: B
Student 3: A+
Student 4: C
Student 5: A
